# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://danbiilee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              dnab
  url:               http://danbiilee.github.io
  email:             danbi.db@gmail.com

# Gems
plugins:
  - jekyll-paginate
paginate: 5


# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
